import assert from "node:assert/strict";
import test from "node:test";

import {
  NEXT_GENERATION_B_FROZEN_CONTINUOUS_CONFIG,
  NEXT_GENERATION_B_FROZEN_SIGNAL_CONFIG,
  NEXT_GENERATION_C_CONTEXT_PRIOR_STD_DEV,
  NEXT_GENERATION_C_FREEZE_AT,
  NEXT_GENERATION_C_FREEZE_POLICY,
  NEXT_GENERATION_C_FROZEN_CONTINUOUS_CONFIG,
  NEXT_GENERATION_C_FROZEN_SIGNAL_CONFIG,
  NEXT_GENERATION_C_MAX_MULTIPLIER,
  NEXT_GENERATION_C_MINIMUM_EXPOSURE_CELLS,
  NEXT_GENERATION_C_MINIMUM_RANDOM_EVENTS,
  NEXT_GENERATION_C_MIN_MULTIPLIER,
  NEXT_GENERATION_C_MODEL_VERSION,
  NEXT_GENERATION_C_SOLVER_BACKTRACKING_FACTOR,
  NEXT_GENERATION_C_SOLVER_INITIAL_STEP,
  NEXT_GENERATION_C_SOLVER_MAX_BACKTRACKING_STEPS,
  NEXT_GENERATION_C_SOLVER_MAX_ITERATIONS,
  NEXT_GENERATION_C_SOLVER_TOLERANCE,
} from "../data/shadowProbabilityConfig";

test("C identity and frozen context constants match the preregistration", () => {
  assert.equal(NEXT_GENERATION_C_MODEL_VERSION, "hazard-contextual-burst-circadian-v1");
  assert.equal(NEXT_GENERATION_C_FREEZE_AT, "2026-08-22T06:15:00.000Z");
  assert.equal(
    NEXT_GENERATION_C_FREEZE_POLICY,
    "A single reset, miss, or new observation must not trigger retuning.",
  );
  assert.equal(NEXT_GENERATION_C_CONTEXT_PRIOR_STD_DEV, 0.5);
  assert.equal(NEXT_GENERATION_C_MINIMUM_RANDOM_EVENTS, 15);
  assert.equal(NEXT_GENERATION_C_MINIMUM_EXPOSURE_CELLS, 720);
  assert.equal(NEXT_GENERATION_C_MIN_MULTIPLIER, 0.5);
  assert.equal(NEXT_GENERATION_C_MAX_MULTIPLIER, 2);
  assert.equal(NEXT_GENERATION_C_SOLVER_MAX_ITERATIONS, 250);
  assert.equal(NEXT_GENERATION_C_SOLVER_TOLERANCE, 1e-7);
  assert.equal(NEXT_GENERATION_C_SOLVER_INITIAL_STEP, 1);
  assert.equal(NEXT_GENERATION_C_SOLVER_BACKTRACKING_FACTOR, 0.5);
  assert.equal(NEXT_GENERATION_C_SOLVER_MAX_BACKTRACKING_STEPS, 24);
});

test("C copies the frozen B Gaussian baseline and exactly reuses the frozen signal policy", () => {
  assert.deepEqual(NEXT_GENERATION_C_FROZEN_CONTINUOUS_CONFIG, NEXT_GENERATION_B_FROZEN_CONTINUOUS_CONFIG);
  assert.notEqual(NEXT_GENERATION_C_FROZEN_CONTINUOUS_CONFIG, NEXT_GENERATION_B_FROZEN_CONTINUOUS_CONFIG);
  assert.deepEqual(NEXT_GENERATION_C_FROZEN_SIGNAL_CONFIG, NEXT_GENERATION_B_FROZEN_SIGNAL_CONFIG);
});
